name: Java CI with Maven

on:
  push:
    branches: master
  
jobs:
  build: 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Listing all generated files
      run: ls -la target/
      
    - name: SCP Files
      # You may pin to the exact commit or the version.
      # uses: appleboy/scp-action@b476d5806f2a4c1ed5902a87fa91b0623cac7258
      uses: wangyucode/sftp-upload-action@v1.1
      with:
         host: cloud.professorisidro.com.br
         port: 22
         username: root
         password: ${{ secrets.PASSWORD }}
         localDir: target/democicd-0.0.1-SNAPSHOT.jar
         remoteDir: /root/
    
      
